// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `CreateCallLog`. */
export interface ICreateCallLogResult {
    id: number;
    created_at: string;
}

/** Result of query `ListCallLogs`. */
export interface IListCallLogsResult {
    id: ICallLogColumns["id"];
    created_at: ICallLogColumns["created_at"];
}

/** Result of query `CountCallLogs`. */
export interface ICountCallLogsResult {
    count: number;
}

export interface Queries {
    CreateCallLog: ICreateCallLogResult;
    ListCallLogs: IListCallLogsResult;
    CountCallLogs: ICountCallLogsResult;
}

/** Columns of `call_log`. */
export interface ICallLogColumns {
    id: number;
    created_at: string;
}

/** Schema of `call_log`. */
export interface ICallLogTable {
    columns: ICallLogColumns;
    relationType: (typeof schema)["call_log"]["_relationType"];
    indexes: keyof (typeof schema)["call_log"]["_indexes"];
    constraints: keyof (typeof schema)["call_log"]["_constraints"];
}

export const schema = {
    call_log: {
        _relationName: "call_log",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} }
        },
        _indexes: {},
        _constraints: {}
    }
} as const;

export interface Tables {
    call_log: ICallLogTable;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
    interface DatabaseTables extends Tables {
    }
}

export {};
